
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - eventtracker.litmuschaos.io
  resources:
  - eventtrackerpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventtracker.litmuschaos.io
  resources:
  - eventtrackerpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - eventtracker.litmuschaos.io
  resources:
  - eventtrackerpolicies/status
  verbs:
  - get
  - patch
  - update
