---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: #{AGENT-NAMESPACE}
data:
  containerRuntimeExecutor: #{ARGO-CONTAINER-RUNTIME-EXECUTOR}
  executor: |
    imagePullPolicy: IfNotPresent
  instanceID: #{CLUSTER_ID}