apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalogue
  labels:
    name: catalogue
    k8s-app: catalogue
  namespace: sock-shop
spec:
  jobLabel: name
  selector:
    matchLabels:
      name: catalogue
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - port: web
    interval: 1s
