apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front-end
  labels:
    name: front-end
    k8s-app: front-end
  namespace: sock-shop
spec:
  jobLabel: name
  selector:
    matchLabels:
      name: front-end
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - port: web
    interval: 1s
