apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders
  labels:
    name: orders
    k8s-app: orders
  namespace: sock-shop
spec:
  jobLabel: name
  selector:
    matchLabels:
      name: orders
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - port: web
    interval: 1s
