apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment
  labels:
    name: payment
    k8s-app: payment
  namespace: sock-shop
spec:
  jobLabel: name
  selector:
    matchLabels:
      name: payment
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - port: web
    interval: 1s
