apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shipping
  labels:
    name: shipping
    k8s-app: shipping
  namespace: sock-shop
spec:
  jobLabel: name
  selector:
    matchLabels:
      name: shipping
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - port: web
    interval: 1s
