apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user
  labels:
    name: user
    k8s-app: user
  namespace: sock-shop
spec:
  jobLabel: name
  selector:
    matchLabels:
      name: user
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - port: web
    interval: 1s
